/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diseniocanales;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author bratc
 */
public class CanalTrapezoidal extends javax.swing.JFrame {
    DecimalFormat df = new DecimalFormat("0.0000");
        
    /**
     * Creates new form CanalTrapezoidal
     */
    public CanalTrapezoidal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCaudal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jVelocidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jBase = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jProfundidad = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPendiente = new javax.swing.JLabel();
        calcular = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jRadioHidraulico = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLocation(new java.awt.Point(200, 200));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                exitCanalTrapezoidal(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("CANAL TRAPEZOIDAL");

        jCaudal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCaudalActionPerformed(evt);
            }
        });

        jLabel2.setText("Caudal (m³/s)");

        jLabel3.setText("Velocidad (m/s)");

        jVelocidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVelocidadActionPerformed(evt);
            }
        });

        jLabel4.setText("Rugosidad : 0.02");

        jLabel5.setText("Talud : 1");

        jLabel6.setText("SALIDA");

        jLabel7.setText("Base (m):");

        jBase.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jBase.setText("0");

        jLabel9.setText("Profundidad (m):");

        jProfundidad.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jProfundidad.setText("0");

        jLabel11.setText("Pendiente:");

        jPendiente.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jPendiente.setText("0");

        calcular.setText("Calcular");
        calcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcularMouseClicked(evt);
            }
        });
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        jLabel8.setText("Radio Hidraulico");

        jRadioHidraulico.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jRadioHidraulico.setText("0");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canalTrapezoidal.jpg"))); // NOI18N

        jButton1.setText("Limpiar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCaudal, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(calcular)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPendiente))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jProfundidad))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioHidraulico))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBase)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(98, 98, 98))))
            .addGroup(layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCaudal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jBase))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jProfundidad))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jRadioHidraulico))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jPendiente)))
                    .addComponent(jLabel10))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCaudalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCaudalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCaudalActionPerformed

    private void jVelocidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVelocidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jVelocidadActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calcularActionPerformed

    private void calcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcularMouseClicked
        // TODO add your handling code here:
        
        boolean validaNumeros = true;
        if(isNumeric(this.jCaudal.getText())!= true){
            JOptionPane.showMessageDialog(null, "Ingrese un valor numérico en el campo Caudal");
            validaNumeros = false;
        } 
        
        if(isNumeric(this.jVelocidad.getText())!= true){
            JOptionPane.showMessageDialog(null, "Ingrese un valor numérico en el campo de Velocidad");
             validaNumeros = false;
        }
       
        if( validaNumeros){
            float caudal = Float.parseFloat(this.jCaudal.getText());
            float velocidad = Float.parseFloat(this.jVelocidad.getText());
            final int TALUD = 1;
            final float RUGOSIDAD =  (float) 0.02;
            float area = (float) (caudal / velocidad);
            float base = (float) Math.sqrt(area/2);
            float tirante = base;
            float profundidad = (float) (tirante * 1.25); 
            float radioHidraulico = (float) (area / (base + (2 * tirante) * Math.sqrt(2))); 

            float pendiente = (float) Math.pow(velocidad * RUGOSIDAD / (float) Math.pow(radioHidraulico,0.6666),2);

            this.jBase.setText(this.df.format(base));
            this.jProfundidad.setText(this.df.format(profundidad));
            this.jPendiente.setText(this.df.format(pendiente));
            this.jRadioHidraulico.setText(this.df.format(radioHidraulico));

             if(velocidad >= 1){
                JOptionPane.showMessageDialog(null,"El canal debe ser revestido");
            }else{
                JOptionPane.showMessageDialog(null, "El canal puede ser construido en condiciones naturales");
            }
        }
    }//GEN-LAST:event_calcularMouseClicked
private static boolean isNumeric(String cadena){
	try {
		Float.parseFloat(cadena);
		return true;
	} catch (NumberFormatException nfe){
		return false;
	}
}
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        this.jCaudal.setText("");
        this.jVelocidad.setText("");
        this.jBase.setText("0");
        this.jProfundidad.setText("0");
        this.jPendiente.setText("0");
        this.jRadioHidraulico.setText("0");
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void exitCanalTrapezoidal(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitCanalTrapezoidal
        // TODO add your handling code here:
    }//GEN-LAST:event_exitCanalTrapezoidal

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CanalTrapezoidal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CanalTrapezoidal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CanalTrapezoidal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CanalTrapezoidal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CanalTrapezoidal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcular;
    private javax.swing.JLabel jBase;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jCaudal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jPendiente;
    private javax.swing.JLabel jProfundidad;
    private javax.swing.JLabel jRadioHidraulico;
    private javax.swing.JTextField jVelocidad;
    // End of variables declaration//GEN-END:variables
}
